# Generated by Django 4.2.3 on 2023-07-25 09:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('category', models.CharField(choices=[("Children's literature", "Children's literature"), ('Fiction', 'Fiction'), ('Historical Fiction', 'Historical Fiction'), ('Science fiction', 'Science fiction'), ('Mystery', 'Mystery'), ('Memoir', 'Memoir'), ('Thriller', 'Thriller'), ('Humor', 'Humor'), ('Romance novel', 'Romance novel')], max_length=50)),
                ('author', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover_image', models.ImageField(upload_to='book_covers/')),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
