# Generated by Django 4.2.3 on 2023-07-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_category_alter_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='date_added',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('By courier', 'By courier'), ('From courier office', 'From courier office'), ('Supplier', 'Supplier')], null=True),
        ),
    ]
