# Generated by Django 4.2.3 on 2023-07-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_deliveryaddress_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('By courier', 'By courier'), ('From courier office', 'From courier office'), ('Supplier', 'Supplier')], default='By courier', null=True),
        ),
    ]
