# Generated by Django 4.2.3 on 2023-07-30 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_deliveryaddress_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
