# Generated by Django 4.2.3 on 2023-07-30 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('book', '0006_bookreview_downvotes_bookreview_upvotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='AppUser',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='upvotes',
        ),
    ]
