# Generated by Django 4.2.3 on 2023-07-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('book', '0007_rename_customer_appuser_remove_bookreview_downvotes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='Customer',
        ),
    ]
