# Generated by Django 4.2.3 on 2023-07-30 22:20

import django.core.validators
from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), validators.validate_letters_only]),
        ),
    ]
