# Generated by Django 4.2.3 on 2023-08-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
