# Generated by Django 4.2.3 on 2023-08-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_remove_orderitem_book_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
