# Generated by Django 4.2.3 on 2023-08-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_customer_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='site_color_theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('dark', 'Dark Mode'), ('light', 'Light Mode')], default='classic', max_length=10),
        ),
    ]
