# Generated by Django 4.2.3 on 2023-08-07 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_alter_bookreview_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='site_color_theme',
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
