# Generated by Django 4.2.3 on 2023-08-09 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_remove_customer_name_delete_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='delivery_address',
        ),
    ]
