# Generated by Django 4.2.3 on 2023-08-10 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_customer_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
